version: "3.8"

services:
  cache:
    image: redis:8.2.1-alpine
    container_name: n8n_cache
    hostname: cache
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    environment:
      - REDIS_PASSWORD=${R_PASSWORD}
      - REDIS_PORT=${R_PORT}
    networks:
      default:
        ipv4_address: 10.10.80.4
    volumes:
      - cache:/data

  db:
    image: postgres:13.22-alpine
    container_name: n8n_db
    hostname: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_POSTGRESDB_USER}
      - POSTGRES_PASSWORD=${DB_POSTGRESDB_PASSWORD}
      - POSTGRES_DB=${DB_POSTGRESDB_DATABASE}
    networks:
      default:
        ipv4_address: 10.10.80.5
    volumes:
      - db:/var/lib/postgresql/data

  pg_admin4:
    image: dpage/pgadmin4:9.7.0
    container_name: n8n_pgadmin4
    hostname: pgadmin
    restart: always
    ports:
      - "127.0.0.1:5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${DEFAULT_USER_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${DEFAULT_USER_PASSWORD}
    networks:
      default:
        ipv4_address: 10.10.80.6
    volumes:
      - pg_admin4:/var/lib/pgadmin
    depends_on:
      - db

  n8n:
    image: docker.n8n.io/n8nio/n8n:stable
    container_name: n8n_instance
    hostname: n8n
    restart: always
    ports:
      - "127.0.0.1:5678:5678"
    environment:
      - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}   # = n8n.beyond-possible.com
      - N8N_PORT=5678
      - N8N_PROTOCOL=https                     # снаружи у тебя https
      - WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
      - NODE_ENV=production
    env_file:
      - .env
    depends_on:
      - cache
      - db
    networks:
      default:
        ipv4_address: 10.10.80.2
    volumes:
      - n8n_data:/home/node/.n8n
      - ./local-files:/files

volumes:
  db:
    driver: local
  cache:
    driver: local
  pg_admin4:
    driver: local
  n8n_data:
    driver: local

networks:
  default:
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: 10.10.80.0/24
          gateway: 10.10.80.1
